// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';


function updateRow(cell, cells, value) {
  return cells.map((function (cellToCheck) {
                if (cellToCheck[/* id */2] === cell[/* id */2]) {
                  return /* record */[
                          /* userValue */value,
                          /* computedValue : None */0,
                          /* id */cell[/* id */2]
                        ];
                } else {
                  return /* record */[
                          /* userValue */cellToCheck[/* userValue */0],
                          /* computedValue : None */0,
                          /* id */cellToCheck[/* id */2]
                        ];
                }
              }));
}

function updateCell(cell, cells, value) {
  return cells.map((function (row) {
                return updateRow(cell, row, value);
              }));
}

exports.updateRow  = updateRow;
exports.updateCell = updateCell;
/* No side effect */
