// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';


function processCell(cell) {
  return /* record */[
          /* userValue */cell[/* userValue */0],
          /* computedValue : Some */[cell[/* userValue */0]],
          /* id */cell[/* id */2]
        ];
}

function processRow(row) {
  return row.map(processCell);
}

function $$process(grid) {
  return grid.map(processRow);
}

exports.processCell = processCell;
exports.processRow  = processRow;
exports.$$process   = $$process;
/* No side effect */
