// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var Caml_string = require("bs-platform/lib/js/caml_string.js");

function interpretExp(value, _) {
  console.log(value);
  return /* Some */[value];
}

function isPrefixedWithEquals(str) {
  if (str.length) {
    var match = Caml_string.get(str, 0);
    if (match !== 61) {
      return /* false */0;
    } else {
      return /* true */1;
    }
  } else {
    return /* false */0;
  }
}

function isUnresolved(cell) {
  if (cell[/* computedValue */1]) {
    return /* false */0;
  } else {
    return isPrefixedWithEquals(cell[/* userValue */0]);
  }
}

function isEmpty(cell) {
  return +(cell[/* userValue */0] === "");
}

function isResolved(cell) {
  return +(cell[/* computedValue */1] !== /* None */0);
}

function processCell(grid, cell) {
  if (isUnresolved(cell)) {
    return /* record */[
            /* userValue */cell[/* userValue */0],
            /* computedValue */interpretExp(cell[/* userValue */0], grid),
            /* id */cell[/* id */2]
          ];
  } else if (cell[/* userValue */0] === "" || cell[/* computedValue */1] !== /* None */0) {
    return /* record */[
            /* userValue */cell[/* userValue */0],
            /* computedValue : Some */[cell[/* userValue */0]],
            /* id */cell[/* id */2]
          ];
  } else {
    return /* record */[
            /* userValue */cell[/* userValue */0],
            /* computedValue : Some */[cell[/* userValue */0]],
            /* id */cell[/* id */2]
          ];
  }
}

function $$process(grid) {
  return grid.map((function (row) {
                return row.map((function (param) {
                              return processCell(grid, param);
                            }));
              }));
}

exports.interpretExp         = interpretExp;
exports.isPrefixedWithEquals = isPrefixedWithEquals;
exports.isUnresolved         = isUnresolved;
exports.isEmpty              = isEmpty;
exports.isResolved           = isResolved;
exports.processCell          = processCell;
exports.$$process            = $$process;
/* No side effect */
