// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe             = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact            = require("reason-react/lib/js/src/reasonReact.js");
var Grid$ReasonSpreadsheet = require("./components/grid.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Grid$ReasonSpreadsheet.make(/* array */[])), "index");

/*  Not a pure module */
